version: '3.7'
services:

  back_end:
    build: .
    ports:
      - 5002:5002
      - 5003:5003
    environment:
      SD_SECRET_KEY: ${SD_SECRET_KEY}
      SD_DB_USERNAME: ${SD_DB_USERNAME}
      SD_DB_PASSWORD: ${SD_DB_PASSWORD}

  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${SD_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${SD_DB_PASSWORD}

volumes:
  mongo_data: